#!/bin/sh

echo
echo " ********************************************************"
echo " * "
echo " * This server is configured using Ansible."
echo " * "
echo " ********************************************************"
echo
