#!/bin/sh

echo
echo " ********************************************************"
echo " * "
echo " * This is the vagrant box of docs.plone.org."
echo " * "
echo " ********************************************************"
echo
