docs_dir: docs/source
site_dir: docs/site
site_name: mr.publisher
repo_url: https://github.com/svx/mr.publisher
site_description: building and deploying documentation
pages:
- ['index.md', 'Introduction']
- ['install.md', 'Install']
- ['user-guide/building.md', 'User Guide', 'Building Documentation']
- ['user-guide/vagrant.md', 'User Guide', 'Vagrant']
- ['user-guide/docker.md', 'User Guide', 'Docker']
- ['user-guide/deployment.md', 'User Guide', 'Deployment']
- ['about/this_docs.md', 'About', 'This docs']
