---

- name: Installs a base Ubuntu 14.04 Server
  hosts: all
  user: vagrant
  sudo: yes

  roles:
      #- apt-update
      #- apt-upgrade
   - ubuntu_packages
   - motd
   - nginx   

  handlers:
   - include: handlers/main.yml
