---
# This role will install, configure and restart nxinx

- name: Install Nginx
  apt: name={{item}} state=present
  with_items:
    - nginx

- name: Upload global.conf
  action: copy src=../files/global.conf dest=/etc/nginx/golbal.conf

- name: Upload nginx.conf
  action: copy src=../files/nginx.conf dest=/etc/nginx/nginx.conf
  notify: start nginx

- name: Upload site config
  action: copy src=../files/sites-available/docs.plone.org
          dest=/etc/nginx/sites-available/docs.plone.org

- name: Create www dir
  file: path=/var/www/docs.plone.org state=directory

- name: add symlink in nginx sites-enabled
  file: src=/etc/nginx/sites-available/docs.plone.org
        dest=/etc/nginx/sites-enabled/docs.plone.org state=link

- name: Deactivate the default nginx site
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  notify: restart nginx
